[build]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/datos"
  to = "/.netlify/functions/datos"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
